import type { ColumnConfig } from "@/types/table"

export const customerColumns: ColumnConfig[] = [
  {
    id: "customerCode",
    dataField: "id", // Map to 'id' which is CUSTOMER_CD
    displayName: "Mã KH",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 0,
  },
  {
    id: "customerNameVi",
    dataField: "nameVi",
    displayName: "Tên KH (VI)",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 1,
  },
  {
    id: "customerNameEn",
    dataField: "nameEn",
    displayName: "Tên KH (EN)",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 2,
  },
  {
    id: "customerNameKo",
    dataField: "nameKo",
    displayName: "Tên KH (KO)",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 3,
  },
  {
    id: "buyerName", // NEW
    dataField: "buyerName",
    displayName: "Tên người mua",
    width: 180,
    visible: true,
    pinned: false,
    originalOrder: 4,
  },
  {
    id: "taxCode",
    dataField: "taxCode",
    displayName: "Mã số thuế",
    width: 150,
    visible: true,
    pinned: false,
    originalOrder: 5,
  },
  {
    id: "email",
    dataField: "email",
    displayName: "Email",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 6,
  },
  {
    id: "tel",
    dataField: "tel",
    displayName: "Điện thoại",
    width: 150,
    visible: true,
    pinned: false,
    originalOrder: 7,
  },
  {
    id: "fax", // NEW
    dataField: "fax",
    displayName: "Fax",
    width: 150,
    visible: true,
    pinned: false,
    originalOrder: 8,
  },
  {
    id: "ownerName", // Existing, but ensure it's here
    dataField: "ownerName",
    displayName: "Tên chủ sở hữu",
    width: 180,
    visible: true,
    pinned: false,
    originalOrder: 9,
  },
  {
    id: "businessType", // Existing
    dataField: "businessType",
    displayName: "Loại hình kinh doanh",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 10,
  },
  {
    id: "kindBusiness", // Existing
    dataField: "kindBusiness",
    displayName: "Ngành nghề",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 11,
  },
  {
    id: "zipCode", // NEW
    dataField: "zipCode",
    displayName: "Mã bưu chính",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 12,
  },
  {
    id: "address",
    dataField: "address",
    displayName: "Địa chỉ",
    width: 250,
    visible: true,
    pinned: false,
    originalOrder: 13,
  },
  {
    id: "notes",
    dataField: "notes",
    displayName: "Ghi chú",
    width: 250,
    visible: true,
    pinned: false,
    originalOrder: 14,
  },
]
